services:
  ldap:
    build:
      context: ./ldap-image
    container_name: shib-ldap-case-c
    environment:
      LDAP_ORGANISATION: "GIdLab"
      LDAP_DOMAIN: "gidlab.rnp.br"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "3890:389"

  shib-idp:
    build: .
    container_name: shib-idp-case-c-standalone
    environment:
      JETTY_BROWSER_SSL_KEYSTORE_PASSWORD: changeme
      JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD: changeme
      JETTY_MAX_HEAP: 1024m
    ports:
      - "4443:4443"
      - "8443:8443"
    depends_on:
      - ldap
    extra_hosts:
      - "host.docker.internal:host-gateway"